version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mambax
    ports:
      - "5432:5432" # Оставляем доступ снаружи для удобства отладки

  backend:
    build: ./backend
    # Команда переопределяется в Dockerfile, но можно явно указать здесь
    # command: ./start.sh
    volumes:
      - ./backend:/app # Монтируем код для Live Reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/mambax
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - db

volumes:
  postgres_data:
