version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mambax-db
    restart: always
    environment:
      POSTGRES_USER: mambax_user
      POSTGRES_PASSWORD: mambax_password
      POSTGRES_DB: mambax_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: mambax-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
